

#ifndef __HPML_AFFINE_TRANSFORMATION_TEMPLATE_INSTANTIATIONS_H__
#define __HPML_AFFINE_TRANSFORMATION_TEMPLATE_INSTANTIATIONS_H__

#include <hpml/affine_transformation/template_definitions.h>

#ifdef __cplusplus
extern "C" {
#endif

/*Begin: Template Instantiations*/
instantiate_declaration_mat4_translation(int);
instantiate_declaration_mat4_scale(int);
instantiate_declaration_mat4_rotation(int); 
instantiate_declaration_mat4_axis_rotation(int); 
instantiate_declaration_mat4_shear(int);
instantiate_declaration_mat4_reflection(int);
instantiate_declaration_mat4_shear_xy(int);
instantiate_declaration_mat4_shear_yx(int);
instantiate_declaration_mat4_shear_zx(int);
instantiate_declaration_mat4_shear_xz(int);
instantiate_declaration_mat4_shear_zy(int);
instantiate_declaration_mat4_shear_yz(int);
instantiate_declaration_mat4_rotation_x(int);
instantiate_declaration_mat4_rotation_y(int);
instantiate_declaration_mat4_rotation_z(int);
instantiate_declaration_mat4_mul_vec4(int);
instantiate_declaration_mat4_ortho_projection(int);
instantiate_declaration_mat4_persp_projection(int);

instantiate_declaration_mat4_translation(float);
instantiate_declaration_mat4_scale(float);
instantiate_declaration_mat4_rotation(float); 
instantiate_declaration_mat4_axis_rotation(float); 
instantiate_declaration_mat4_shear(float);
instantiate_declaration_mat4_reflection(float);
instantiate_declaration_mat4_shear_xy(float);
instantiate_declaration_mat4_shear_yx(float);
instantiate_declaration_mat4_shear_zx(float);
instantiate_declaration_mat4_shear_xz(float);
instantiate_declaration_mat4_shear_zy(float);
instantiate_declaration_mat4_shear_yz(float);
instantiate_declaration_mat4_rotation_x(float);
instantiate_declaration_mat4_rotation_y(float);
instantiate_declaration_mat4_rotation_z(float);
instantiate_declaration_mat4_mul_vec4(float);
instantiate_declaration_mat4_ortho_projection(float);
instantiate_declaration_mat4_persp_projection(float);

#if defined(IMPLEMENTATION)
instantiate_implementation_mat4_translation(int); 
instantiate_implementation_mat4_scale(int); 
instantiate_implementation_mat4_rotation(int); 
instantiate_implementation_mat4_axis_rotation(int); 
instantiate_implementation_mat4_shear(int);
instantiate_implementation_mat4_reflection(int);
instantiate_implementation_mat4_shear_xy(int);
instantiate_implementation_mat4_shear_yx(int);
instantiate_implementation_mat4_shear_zx(int);
instantiate_implementation_mat4_shear_xz(int);
instantiate_implementation_mat4_shear_zy(int);
instantiate_implementation_mat4_shear_yz(int);
instantiate_implementation_mat4_rotation_x(int);
instantiate_implementation_mat4_rotation_y(int);
instantiate_implementation_mat4_rotation_z(int);
instantiate_implementation_mat4_mul_vec4(int);
instantiate_implementation_mat4_ortho_projection(int);
instantiate_implementation_mat4_persp_projection(int);

instantiate_implementation_mat4_translation(float); 
instantiate_implementation_mat4_scale(float); 
instantiate_implementation_mat4_rotation(float); 
instantiate_implementation_mat4_axis_rotation(float); 
instantiate_implementation_mat4_shear(float);
instantiate_implementation_mat4_reflection(float);
instantiate_implementation_mat4_shear_xy(float);
instantiate_implementation_mat4_shear_yx(float);
instantiate_implementation_mat4_shear_zx(float);
instantiate_implementation_mat4_shear_xz(float);
instantiate_implementation_mat4_shear_zy(float);
instantiate_implementation_mat4_shear_yz(float);
instantiate_implementation_mat4_rotation_x(float);
instantiate_implementation_mat4_rotation_y(float);
instantiate_implementation_mat4_rotation_z(float);
instantiate_implementation_mat4_mul_vec4(float);
instantiate_implementation_mat4_ortho_projection(float);
instantiate_implementation_mat4_persp_projection(float);

#endif /*if defined IMPLEMENTATION*/

/*End: Template Instantiations*/

#ifdef __cplusplus
}
#endif /*__cplusplus*/

#endif /*__HPML_AFFINE_TRANSFORMATION_TEMPLATE_INSTANTIATIONS_H__*/